# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ui5RURYNc2cMKYaa6AgKUsDxR_IDHGf0
"""

import streamlit as st
import pandas as pd
from sklearn import datasets

st.write("""
# Summation of 2 numbers
""")
#Get Input

st.header('User Input Parameters')
    
number_1 = st.number_input("Number 1")
number_2 = st.number_input("Number 2")
    
answer = number_1+number_2
st.write ("The answer is:", answer)